../design/defines.svh
../design/crc.sv
../design/deser.sv
../design/ef_utils.v
../design/fec.sv
../design/fec_fsm.sv
../design/reg_cfg.sv
../design/packet.sv
../design/training.sv
../design/uart.sv
../design/dl_fec.sv
../design/dl_ctrl.sv
../design/ul_fec.sv
../design/ul_mon.sv
../design/fec_top.sv
../testbench/tb_macros.svh
../testbench/testbench.sv